Repository wecode-bootcamp-korea/41-1st-Dr.Bean-frontend, pull requests merged in 2023-01, with the labels that each got.

#3 [41기 이진경] Modify : common.scss 파일 inner 변경 완료
  package-lock.json
  package.json
  public/index.html
  src/styles/color.scss
  src/styles/common.scss
  src/styles/variables.scss
Labels: 멘토 리뷰 요청

#4 [41기 이진경] Modify : color.scss 리팩토링 완료
  package-lock.json
  package.json
  public/index.html
  src/styles/color.scss
Labels: 멘토 리뷰 요청

#5 [41기 이진경 ]Modify: common.scss 파일 수정 완료
  src/styles/common.scss
Labels: 멘토 리뷰 요청

#9 [41기 이진경]Add : variables.scss추가 및 color.scss 수정
  src/styles/color.scss
  src/styles/variables.scss
Labels: 멘토 리뷰 요청

#8 [41기 김기윤] Add: 로그인페이지
  src/Router.js
  src/components/RegisterLogin/ContentHeader.jsx
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
Labels: 멘토 리뷰 요청

#11 [41기 이진경] Modify : 오타수정
  src/styles/variables.scss
Labels: 멘토 리뷰 요청

#7 [41기 이진경] Modify :상품 상세 페이지 기능 구현 중
  package-lock.json
  package.json
  public/data/Review.json
  public/images/coffee_bean.jpg
  public/images/coffee_icon.png
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/ProductDetailMain/ProductCount/ProductCount.jsx
  src/pages/ProductDetail/ProductDetailMain/ProductCount/ProductCount.scss
  src/pages/ProductDetail/ProductDetailMain/ProductDetailMain.jsx
  src/pages/ProductDetail/ProductDetailMain/ProductDetailMain.scss
  src/pages/ProductDetail/ProductDetailMain/ProductSelect/ProductSelect.jsx
  src/pages/ProductDetail/ProductDetailMain/ProductSelect/ProductSelect.scss
  src/pages/ProductDetail/ProductReview/ProductReview.jsx
  src/pages/ProductDetail/ProductReview/ProductReview.scss
  src/pages/ProductDetail/ProductReview/ReviewBox/ReviewBox.jsx
  src/pages/ProductDetail/ProductReview/ReviewBox/ReviewBox.scss
  src/pages/ProductDetail/ProductReview/ReviewItem/ReviewItem.jsx
  src/pages/ProductDetail/ProductReview/ReviewItem/ReviewItem.scss
  src/styles/common.scss
  src/styles/variables.scss
Labels: 멘토 리뷰 요청

#14 [41기 박채연] Modify: nav 레이아웃 수정 및 navsidebar 기능구현
  .gitignore
  public/images/dr.bean-logo.png
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/NavSide.js
  src/components/Nav/NavSide.scss
  src/pages/Main/Main.js
Labels: 멘토 리뷰 요청

#6 [41기 박채연] Add: 결제페이지 레이아웃 구성(피드백수정완료)
  src/Router.js
  src/pages/Cart/cart.js
  src/pages/Cart/cart.scss
  src/pages/Payment/Modal.js
  src/pages/Payment/Modal.scss
  src/pages/Payment/Payment.js
  src/pages/Payment/Payment.scss
Labels: 멘토 리뷰 요청

#15 [41기 박채연] Modify: Footer 레이아웃 구현(수정완료 및 기능구현중)
  public/images/footerlog.jpg
  src/Router.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/pages/Payment/test.js
Labels: 멘토 리뷰 요청

#16 [41기 김기윤] Add: 로그인 페이지 완료 (conflict 해결)
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
Labels: 멘토 리뷰 요청

#18 [41기 박채연] footer 레이아웃 재수정
  public/images/dr.bean-logo 2.png
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Nav/NavSide 2.js
  src/components/Nav/NavSide 2.scss
  src/styles/variables 2.scss
Labels: 멘토 리뷰 요청

#2 [41기 이진경] Modify : 메인페이지 기능 구현 완료 (피드백 수정 완료)
  package-lock.json
  package.json
  public/data/Country.json
  public/data/FilterData.json
  public/data/sample.js
  public/images/africa.png
  public/images/asia.png
  public/images/farm.webp
  public/images/north_america.png
  public/images/south_america.png
  src/Router.js
  src/images/main1.avif
  src/images/main2.jpg
  src/images/main3.jpg
  src/images/painter-g891aad3a2_1280.jpg
  src/pages/BrandStory/TIME_LIST.js
  src/pages/Main/Main.js
  src/pages/Main/MainFilter/MainFilter.jsx
  src/pages/Main/MainFilter/MainFilter.scss
  src/pages/Main/MainFilter/MainFilterItem/MainFilterItem.jsx
  src/pages/Main/MainFilter/MainFilterItem/MainFilterItem.scss
  src/pages/Main/MainReview/MainReview.jsx
  src/pages/Main/MainReview/MainReview.scss
  src/pages/Main/MainScroll/MainScroll.jsx
  src/pages/Main/MainScroll/MainScroll.scss
  src/pages/ProductDetail/MainScroll/MainScroll.jsx
  src/pages/ProductDetail/MainScroll/MainScroll.scss
  src/pages/Signup/Signup.js
Labels: 멘토 리뷰 요청

#17 [41기 이진경] ADD : 브랜드 소개 / 예약 폼 구현 완료 (충돌 수정 완료)
  public/images/brandStory_1.jpg
  public/images/brandStory_2.jpg
  public/images/brandStory_3.jpg
  src/Router.js
  src/pages/BrandStory/BrandStory.js
  src/pages/BrandStory/BrandStory.scss
Labels: 멘토 리뷰 요청

#21 [41기 김기윤] 회원가입 페이지 일부수정
  src/pages/Signup/Signup.js
Labels: 멘토 리뷰 요청

#22 [41기 김기윤] 회원가입 페이지 CSS 스타일 업데이트
  src/pages/Signup/Signup.scss
Labels: 멘토 리뷰 요청

#24 [41기 박채연] Footer Modify: 레이아웃수정
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: 멘토 리뷰 요청

#23 [41기 김기윤] 로그인 페이지 오타 수정 및 스타일 수정
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: 멘토 리뷰 요청

#28 [41기 이진경] Add : top button 추가
  src/Router.js
  src/components/TopBtn/TopBtn.jsx
  src/components/TopBtn/TopBtn.scss
Labels: 멘토 리뷰 요청

#29 [41기 김기윤] 로그인 페이지 스타일 수정
  src/components/RegisterLogin/ContentHeader.jsx
  src/pages/Login/Login.scss
Labels: 멘토 리뷰 요청

#25 [41기 박채연] navsidebar url 추가
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/NavArea.jsx
  src/components/Nav/NavSide.js
  src/components/Nav/NavSide.scss
  src/components/Nav/NavsideCountry.jsx
Labels: 멘토 리뷰 요청

#19 [41기 이진경 ]백엔드 서버 통신 완료 (conflict 수정 완료)
  public/data/GramList.json
  src/Router.js
  src/images/brandStory_1.jpg
  src/images/brandStory_2.jpg
  src/pages/Main/MainReview/MainReview.jsx
  src/pages/Main/MainReview/MainReview.scss
  src/pages/ProductDetail/ProductDetailMain/ProductCount/ProductCount.jsx
  src/pages/ProductDetail/ProductDetailMain/ProductDetailMain.jsx
  src/pages/ProductDetail/ProductDetailMain/ProductDetailMain.scss
  src/pages/ProductDetail/ProductDetailMain/ProductSelect/ProductSelect.jsx
  src/pages/ProductDetail/ProductDetailMain/ProductSelect/ProductSelect.scss
  src/pages/ProductDetail/ProductDetailMain/ProductSelect/SELECT_LIST.js
  src/pages/ProductDetail/ProductReview/ProductReview.jsx
  src/pages/ProductDetail/ProductReview/ProductReview.scss
  src/pages/ProductDetail/ProductReview/ReviewItem/ReviewItem.jsx
Labels: 멘토 리뷰 요청

#31 [41기 박채연] nav navigate 수정
  src/components/Nav/Nav.js
  src/components/Nav/NavArea.jsx
Labels: 멘토 리뷰 요청

#26 [41기 박채연] payment 라우터 수정
  src/components/Nav/Nav.js
  src/pages/Payment/Modal.js
Labels: 멘토 리뷰 요청

#32 [41기 이진경] Feature/main border 삭제
  src/pages/Main/MainScroll/MainScroll.scss
Labels: 완료

#33 [41기 박채연] nav 레이아웃수정
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/NavSide.scss
Labels: 멘토 리뷰 요청

#35 [41기 이진경] Modify : 상품 상세 페이지 백엔드 통신 완료(구매)
  src/Router.js
  src/pages/ProductDetail/ProductDetailMain/ProductDetailMain.jsx
  src/pages/ProductDetail/ProductDetailMain/ProductSelect/ProductSelect.jsx
  src/pages/ProductDetail/ProductReview/ProductReview.jsx
  src/styles/variables 2.scss
Labels: 멘토 리뷰 요청

#36 [41기 김기윤] 상품 진열 페이지 일부수정
  src/pages/ProductList/ProductCard.scss
  src/pages/ProductList/ProductListHeader.jsx
Labels: 멘토 리뷰 요청

#38 [41기 이진경] Modify : 사이드바 수정
  src/components/Nav/Nav.scss
  src/components/Nav/NavArea.jsx
  src/components/Nav/NavSide 2.js
  src/components/Nav/NavSide 2.scss
  src/components/Nav/NavSide.js
  src/components/Nav/NavSide.scss
  src/styles/variables.scss
Labels: 멘토 리뷰 요청

#37 [41기 김기윤] 상품 페이지 (숫자 천원 단위 표현 및 뒤로가기 기능 추가)
  src/pages/ProductList/ProductCard.jsx
  src/pages/ProductList/ProductListHeader.jsx
Labels: 멘토 리뷰 요청

#39 [41기 이진경] Modify : 백엔드 통신 완료 / navigate 설정 완료
  src/pages/ProductDetail/ProductDetailMain/ProductCount/ProductCount.jsx
  src/pages/ProductDetail/ProductDetailMain/ProductDetailMain.jsx
Labels: 멘토 리뷰 요청

#40 [41기 이진경] Modify : 페이지 이동시 사이드바 false 처리
  src/components/Nav/Nav.js
  src/components/Nav/NavSide.js
  src/components/Nav/NavSide.scss
Labels: 멘토 리뷰 요청

#27 [41기 박채연] 통신완료 및 기능 구현 완료
  src/Router.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/cart.js
  src/pages/Cart/cart.scss
  src/pages/Login/Login.js
  src/pages/Payment/Modal.js
  src/pages/Payment/Payment.js
  src/pages/Payment/test.js
  src/pages/ProductDetail/ProductDetailMain/ProductDetailMain.jsx
Labels: 멘토 리뷰 요청

#34 [41기 박채연] footer 피드백 수정완료
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: 멘토 리뷰 요청

#41 [41기 김기윤] 회원가입 페이지 일부수정 (전화번호 데이터유형 변경)
  src/pages/Signup/Signup.js
Labels: 멘토 리뷰 요청

#42 [41기 이진경] Modify : 포인트 금액 고정 지정
  src/pages/Signup/Signup.js
Labels: 멘토 리뷰 요청

#43 [41기 박채연 ] payment 통신 및 기능구현 완료
  src/pages/Cart/Cart.js
  src/pages/Payment/Modal.js
  src/pages/Payment/Modal.scss
  src/pages/Payment/Payment.js
  src/pages/Payment/Payment.scss
  src/pages/ProductDetail/ProductDetailMain/ProductDetailMain.jsx
Labels: 멘토 리뷰 요청

#45 [41기 박채연 ] map오류 수정
  src/pages/Payment/Modal.js
  src/pages/Payment/Payment.js
Labels: 멘토 리뷰 요청

#44 [41기 이진경] Modiify : 최종 수정 완료
  src/components/Nav/Nav.scss
  src/components/Nav/NavArea.jsx
  src/pages/Login/Login.js
  src/pages/Main/MainFilter/MainFilter.jsx
  src/pages/Main/MainFilter/MainFilterItem/MainFilterItem.jsx
  src/pages/ProductDetail/ProductReview/ProductReview.jsx
  src/pages/ProductList/ProductListHeader.jsx
  src/pages/Signup/Signup.js
Labels: 멘토 리뷰 요청

#48 [41기 이진경] Feature/product detail
  src/pages/Cart/Cart.js
  src/pages/ProductDetail/ProductDetailMain/ProductDetailMain.jsx
Labels: 멘토 리뷰 요청

#49 [41기 김기윤] Update README.md
  README.md
Labels: 멘토 리뷰 요청

#47 [41기 김기윤] 로그인페이지 navigate 수정
  src/pages/Login/Login.js
Labels: Conflict 해결 요청
